# Generated by Django 5.2.8 on 2026-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_alter_studynote_unique_together_studynote_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='selbstbewertung',
            field=models.IntegerField(default=0),
        ),
    ]
